### ISSUE TITLE
CSS rewrite

### ISSUE THREAD

**Issue by tterian** [spacehelmet/talenthub#14]
Styling should undergo a major rewrite. There are lots of duplicates and repetitions, so there should be a common styleguide to be developed and enforced to every component/page.

For example there should be a container class with following styling

```css
.container {
    margin: auto;
    max-width: 55em;
    padding: 10px 0;
    text-align: center;
}
```

The same thing should be done for
```
sections
typograpy tags
buttons
flex blocks
```
